# Generated by Django 6.1 on 2026-08-24 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('FIC', 'fiction'), ('HIS', 'history'), ('SCI', 'science'), ('ROM', 'romance')], max_length=50)),
                ('price', models.DecimalField()),
                ('author', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.authors')),
                ('publisher', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.publishers')),
            ],
        ),
    ]
