# Generated by Django 6.1 on 2026-08-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publication_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
